spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 208941
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    secret-key: OrTrTcACcKYJp+86Qm1ZjKWiQ3/2Hh+EN9MB91HORmxl1Ueacaisi1onquFmOESebsAE4jwQY/WEMsC/wwL56w==

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志输出
  mapper-locations: classpath*:com/wjx/database/mapper/xml/**.xml